services:
  - type: web
    name: ecocore-api
    env: python
    repo: https://github.com/Harsh-Aaryan/EcoAI.git
    branch: main
    rootDir: ecocore/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: ecocore
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.12"
